# action.yml
name: 'Git Commit Standards'
description: 'Ensure commit messages follow the conventional commit standard'
inputs:
  must-have-subject-line:
    description: 'Whether the commit message must have a subject line'
    required: false
    default: true
  subject-line-capitalised:
    description: 'Whether the first word in the subject line must be capitalised'
    required: false
    default: true
  no-period-at-end-of-subject-line:
    description: 'Whether the subject line must not end with a period'
    required: false
    default: true
  first-word-in-subject-line-must-be-imperative-verb:
    description: 'Whether the first word in the subject line must be an imperative verb'
    required: false
    default: true
  body-must-have-blank-line:
    description: 'Whether the body must have a blank line between it and the subject line (default is true)'
    required: false
    default: true
  body-line-max-length:
    description: 'The maximum length of a line in the body (default is 72 characters)'
    required: false
    default: 72
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.must-have-subject-line }}
    - ${{ inputs.subject-line-capitalised }}
    - ${{ inputs.no-period-at-end-of-subject-line }}
    - ${{ inputs.first-word-in-subject-line-must-be-imperative-verb }}
    - ${{ inputs.body-must-have-blank-line }}
    - ${{ inputs.body-line-max-length }}
