#!/bin/sh -l

set -e

# Arguments from action.yml
MUST_HAVE_SUBJECT_LINE=$1
SUBJECT_LINE_CAPITALISED=$2
NO_PERIOD_AT_END_OF_SUBJECT_LINE=$3
FIRST_WORD_IN_SUBJECT_LINE_IS_IMPERATIVE_VERB=$4
BODY_MUST_HAVE_BLANK_LINE=$5
BODY_MUST_BE_WRAPPED_AT_72_CHARACTERS=$6

echo "MUST_HAVE_SUBJECT_LINE=$MUST_HAVE_SUBJECT_LINE"
echo "SUBJECT_LINE_CAPITALISED=$SUBJECT_LINE_CAPITALISED"
echo "NO_PERIOD_AT_END_OF_SUBJECT_LINE=$NO_PERIOD_AT_END_OF_SUBJECT_LINE"
echo "FIRST_WORD_IN_SUBJECT_LINE_IS_IMPERATIVE_VERB=$FIRST_WORD_IN_SUBJECT_LINE_IS_IMPERATIVE_VERB"
echo "BODY_MUST_HAVE_BLANK_LINE=$BODY_MUST_HAVE_BLANK_LINE"
echo "BODY_MUST_BE_WRAPPED_AT_72_CHARACTERS=$BODY_MUST_BE_WRAPPED_AT_72_CHARACTERS"

time=$(date)
echo "time=$time" >> $GITHUB_OUTPUT