#!/bin/sh -l

set -e

# Arguments from action.yml
MUST_HAVE_SUBJECT_LINE=$1
SUBJECT_LINE_CAPITALISED=$2
NO_PERIOD_AT_END_OF_SUBJECT_LINE=$3
FIRST_WORD_IN_SUBJECT_LINE_MUST_BE_IMPERATIVE_VERB=$4
BODY_MUST_HAVE_BLANK_LINE=$5
BODY_MAX_LENGTH=$6

# Handle each argument
if [ "$MUST_HAVE_SUBJECT_LINE" ]; then
  echo "MUST_HAVE_SUBJECT_LINE=$MUST_HAVE_SUBJECT_LINE"
fi

if [ "$SUBJECT_LINE_CAPITALISED" ]; then
  echo "SUBJECT_LINE_CAPITALISED=$SUBJECT_LINE_CAPITALISED"
fi

if [ "$NO_PERIOD_AT_END_OF_SUBJECT_LINE" ]; then
  echo "NO_PERIOD_AT_END_OF_SUBJECT_LINE=$NO_PERIOD_AT_END_OF_SUBJECT_LINE"
fi

if [ "$FIRST_WORD_IN_SUBJECT_LINE_MUST_BE_IMPERATIVE_VERB" ]; then
  echo "FIRST_WORD_IN_SUBJECT_LINE_MUST_BE_IMPERATIVE_VERB=$FIRST_WORD_IN_SUBJECT_LINE_MUST_BE_IMPERATIVE_VERB"
fi

if [ "$BODY_MUST_HAVE_BLANK_LINE" ]; then
  echo "BODY_MUST_HAVE_BLANK_LINE=$BODY_MUST_HAVE_BLANK_LINE"
fi

if [ "$BODY_MAX_LENGTH" ]; then
  echo "BODY_MAX_LENGTH=$BODY_MAX_LENGTH"
fi

time=$(date)
echo "time=$time" >> $GITHUB_OUTPUT